#!/usr/bin/env python3
"""Generate architecture documentation from tach analysis.

Creates:
- docs/architecture/dependency_graph.html - Interactive visual diagram
- docs/architecture/dependency_report.html - Detailed dependency report
"""

import subprocess
import sys
from pathlib import Path


def run_command(cmd: list[str]) -> str:
    """Run a command and return stdout."""
    result = subprocess.run(cmd, capture_output=True, text=True, cwd=Path(__file__).parent.parent)
    return result.stdout


def get_mermaid_diagram() -> str:
    """Get mermaid diagram from tach."""
    output = run_command(["tach", "show", "--mermaid", "-o", "-"])
    lines = output.strip().split("\n")
    diagram_lines = []
    for line in lines:
        if line.startswith("NOTE:") or line.startswith("To visualize"):
            break
        diagram_lines.append(line)
    return "\n".join(diagram_lines)


def get_dependency_report(module_path: str) -> str:
    """Get dependency report for a module."""
    output = run_command(["tach", "report", module_path, "--dependencies", "--usages"])
    return output


def generate_graph_html(mermaid_content: str) -> str:
    """Generate the dependency graph HTML."""
    return f'''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MCP Server Filesystem - Dependency Graph</title>
    <script src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            margin: 0;
            padding: 20px;
            background: #1a1a2e;
            color: #eee;
        }}
        h1 {{
            text-align: center;
            color: #00d9ff;
            margin-bottom: 10px;
        }}
        .subtitle {{
            text-align: center;
            color: #888;
            margin-bottom: 30px;
        }}
        .legend {{
            display: flex;
            justify-content: center;
            gap: 20px;
            margin-bottom: 20px;
            flex-wrap: wrap;
        }}
        .legend-item {{
            display: flex;
            align-items: center;
            gap: 8px;
            padding: 8px 16px;
            background: #252540;
            border-radius: 8px;
        }}
        .legend-color {{
            width: 16px;
            height: 16px;
            border-radius: 4px;
        }}
        .mermaid {{
            display: flex;
            justify-content: center;
            background: #16213e;
            border-radius: 12px;
            padding: 30px;
            overflow: auto;
        }}
        .info {{
            max-width: 800px;
            margin: 30px auto;
            padding: 20px;
            background: #252540;
            border-radius: 12px;
        }}
        .info h2 {{
            color: #00d9ff;
            margin-top: 0;
        }}
        .info ul {{
            line-height: 1.8;
        }}
        code {{
            background: #1a1a2e;
            padding: 2px 6px;
            border-radius: 4px;
            color: #00d9ff;
        }}
        a {{
            color: #00d9ff;
        }}
    </style>
</head>
<body>
    <h1>MCP Server Filesystem - Module Dependency Graph</h1>
    <p class="subtitle">Generated by tach - Architectural Boundary Enforcement | <a href="dependency_report.html">View Detailed Report</a></p>

    <div class="legend">
        <div class="legend-item">
            <div class="legend-color" style="background: #ff6b6b;"></div>
            <span>Entry (main)</span>
        </div>
        <div class="legend-item">
            <div class="legend-color" style="background: #4ecdc4;"></div>
            <span>Protocol (server)</span>
        </div>
        <div class="legend-item">
            <div class="legend-color" style="background: #45b7d1;"></div>
            <span>Tools (file_tools)</span>
        </div>
        <div class="legend-item">
            <div class="legend-color" style="background: #96ceb4;"></div>
            <span>Utilities (log_utils)</span>
        </div>
    </div>

    <div class="mermaid">
{mermaid_content}
    </div>

    <div class="info">
        <h2>Architecture Layers</h2>
        <ul>
            <li><strong>Entry</strong> - Application entry point (<code>main.py</code>)</li>
            <li><strong>Protocol</strong> - MCP server implementation (<code>server.py</code>)</li>
            <li><strong>Tools</strong> - File operation tool implementations (<code>file_tools/</code>)</li>
            <li><strong>Utilities</strong> - Shared utilities (<code>log_utils.py</code>)</li>
        </ul>

        <h2>Commands</h2>
        <ul>
            <li><code>tach check</code> - Verify architectural boundaries</li>
            <li><code>tools\\tach_check.bat</code> - Run boundary check</li>
            <li><code>tools\\tach_docs.bat</code> - Regenerate this documentation</li>
        </ul>
    </div>

    <script>
        mermaid.initialize({{
            startOnLoad: true,
            theme: 'dark',
            flowchart: {{
                useMaxWidth: true,
                htmlLabels: true,
                curve: 'basis'
            }}
        }});
    </script>
</body>
</html>
'''


def generate_report_html(reports: dict[str, str]) -> str:
    """Generate the detailed report HTML."""
    return f'''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MCP Server Filesystem - Dependency Report</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            margin: 0;
            padding: 20px;
            background: #1a1a2e;
            color: #eee;
        }}
        h1 {{
            text-align: center;
            color: #00d9ff;
            margin-bottom: 10px;
        }}
        .subtitle {{
            text-align: center;
            color: #888;
            margin-bottom: 30px;
        }}
        a {{ color: #00d9ff; }}
        .toc {{
            max-width: 800px;
            margin: 0 auto 30px;
            padding: 20px;
            background: #252540;
            border-radius: 12px;
        }}
        .toc h2 {{ color: #00d9ff; margin-top: 0; }}
        .module-report {{
            max-width: 1200px;
            margin: 20px auto;
            padding: 20px;
            background: #252540;
            border-radius: 12px;
        }}
        .module-report h2 {{
            color: #00d9ff;
            margin-top: 0;
            padding-bottom: 10px;
            border-bottom: 1px solid #444;
        }}
        pre {{
            background: #1a1a2e;
            padding: 15px;
            border-radius: 8px;
            overflow-x: auto;
            font-size: 13px;
            line-height: 1.5;
        }}
    </style>
</head>
<body>
    <h1>MCP Server Filesystem - Dependency Report</h1>
    <p class="subtitle">Detailed import-level dependencies and usages | <a href="dependency_graph.html">View Graph</a></p>

    <div class="toc">
        <h2>Modules</h2>
        <ul>
            {''.join(f'<li><a href="#{m.replace(".", "-")}">{m}</a></li>' for m in reports.keys())}
        </ul>
    </div>

    {''.join(f'<div class="module-report" id="{m.replace(".", "-")}"><h2>{m}</h2><pre>{r.replace("<", "&lt;").replace(">", "&gt;")}</pre></div>' for m, r in reports.items())}
</body>
</html>
'''


def main() -> int:
    """Generate architecture documentation."""
    print("Generating architecture documentation...")

    output_dir = Path(__file__).parent.parent / "docs" / "architecture"
    output_dir.mkdir(parents=True, exist_ok=True)

    print("  - Generating dependency graph...")
    graph_html = generate_graph_html(get_mermaid_diagram())
    graph_path = output_dir / "dependency_graph.html"
    graph_path.write_text(graph_html, encoding="utf-8")
    print(f"    Created: {graph_path}")

    print("  - Generating dependency reports...")
    modules = [
        "src/mcp_workspace/main.py",
        "src/mcp_workspace/server.py",
        "src/mcp_workspace/file_tools",
        "src/mcp_workspace/log_utils.py",
    ]

    reports = {}
    for module in modules:
        module_name = module.replace("src/", "").replace("/", ".").rstrip(".py")
        print(f"    - {module_name}")
        reports[module_name] = get_dependency_report(module)

    report_html = generate_report_html(reports)
    report_path = output_dir / "dependency_report.html"
    report_path.write_text(report_html, encoding="utf-8")
    print(f"    Created: {report_path}")

    print("\nDone! Open docs/architecture/dependency_graph.html to view.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
