name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .
        python -m pip install .[dev]
        
    - name: Check formatting with black
      run: |
        black --check src tests
        
    - name: Check imports with isort
      run: |
        isort --check --profile=black --float-to-top src tests
        
    - name: Check for errors with pylint
      run: |
        pylint -E ./src ./tests
        
    - name: Run tests
      run: |
        pytest tests
